### ISSUE TITLE
Crash upon entering Pale Garden biome

### ISSUE THREAD

**Issue by morganfaire** [Haven-King/Atmosfera#42] opened 2024-12-14 23:51 UTC
Exactly what it sounds like, every time I enter the Pale Garden with this mod installed the game crashes.

**Comment by Fourmisain** [comment] 2024-12-15 12:35
And you're using 2.0.1+mc1.21.4?
I can't seem to reproduce the issue, it fades out the music like it's supposed to.
Do you have a crash report or latest.log for me to look at?

...

I just get a crash on world generation, but that may be unrelated - unsure what's that about, game is giving little hints.

**Comment by Fourmisain** [comment] 2024-12-15 13:09
Figured out where the latter crash came from - the way Atmosfera wants to play sounds is not thread-safe. This has apparently been an issue for ages, though since it hasn't been reported yet, it may only be a rare occurence.

It's also almost surely not related to your issue, which I still can't reproduce.

**Comment by Fourmisain** [comment] 2024-12-15 13:16
Hold on, I think I have an idea what the issue may be!

**Comment by Fourmisain** [comment] 2024-12-21 20:01
I published a new version 2.1.0 (more or less the same as the test release).
Still not sure if this fixes your issue, so let me know if it doesn't, including the crash log.
Closing this issue for now.

**Closed by Fourmisain** 2024-12-21 20:01 UTC
